# Generated by Django 5.1.5 on 2025-02-05 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='STATE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.PositiveBigIntegerField(auto_created=True, unique=True)),
                ('name', models.CharField(max_length=32)),
                ('mobile', models.PositiveBigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('aadhaar', models.PositiveIntegerField()),
                ('father_name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('address', models.CharField(max_length=1000)),
                ('balance', models.PositiveSmallIntegerField(default=500)),
                ('pin', models.IntegerField(blank=True)),
                ('photo', models.ImageField(upload_to='profile_pics')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.gender')),
                ('states', models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to='app.state')),
            ],
        ),
    ]
